#!/usr/bin/env bash
# This script displays a comprehensive list of all currently running processes.
# It includes processes from all users, those without a TTY, and shows
# them in a user-oriented, hierarchical format.
# 'ps auxf' is used for this purpose:
#   a: show processes for all users
#   u: display user-oriented format
#   x: show processes without a controlling tty
#   f: ASCII art process hierarchy (forest)

ps auxf
