#!/usr/bin/env bash
# This script stops the running '4-to_infinity_and_beyond' process.
# It finds the PID of the target script using 'pgrep -f' and then
# sends a termination signal to that PID using 'kill'.

pgrep -f "4-to_infinity_and_beyond" | xargs kill
