#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, pausing for 2 seconds.
# It handles the SIGTERM signal by printing "I am invincible!!!" and continuing its loop.

trap "echo 'I am invincible!!!'" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
