#!/usr/bin/env bash
# This script displays a message and traps SIGTERM to print a custom message

# Trap SIGTERM and print a message
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
  echo "To infinity and beyond"
  sleep 2
done
