#!/usr/bin/env bash
# This script loops 1 to 10 and shows different messages for specific iterations

i=1

while [ "" -le 10 ]
do
  if [ "" -eq 4 ]; then
    echo "bad luck"
  elif [ "" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done

